// Deck: kanji angka + hubungan manusia
// Cara menambah: salin satu baris { kanji, reading, meaning },
const cards = [
  // --- Angka dasar ---
  { kanji: "一", reading: "いち", meaning: "satu" },
  { kanji: "二", reading: "に", meaning: "dua" },
  { kanji: "三", reading: "さん", meaning: "tiga" },
  { kanji: "四", reading: "よん・し", meaning: "empat" },
  { kanji: "五", reading: "ご", meaning: "lima" },
  { kanji: "六", reading: "ろく", meaning: "enam" },
  { kanji: "七", reading: "なな・しち", meaning: "tujuh" },
  { kanji: "八", reading: "はち", meaning: "delapan" },
  { kanji: "九", reading: "きゅう・く", meaning: "sembilan" },
  { kanji: "十", reading: "じゅう", meaning: "sepuluh" },
  { kanji: "百", reading: "ひゃく", meaning: "seratus" },
  { kanji: "千", reading: "せん", meaning: "seribu" },
  { kanji: "万", reading: "まん", meaning: "sepuluh ribu" },
  { kanji: "円", reading: "えん", meaning: "yen (mata uang Jepang)" },

  // --- Tanggal ---
  { kanji: "一日", reading: "ついたち", meaning: "tanggal 1" },
  { kanji: "二日", reading: "ふつか", meaning: "tanggal 2" },
  { kanji: "三日", reading: "みっか", meaning: "tanggal 3" },
  { kanji: "四日", reading: "よっか", meaning: "tanggal 4" },
  { kanji: "五日", reading: "いつか", meaning: "tanggal 5" },
  { kanji: "六日", reading: "むいか", meaning: "tanggal 6" },
  { kanji: "七日", reading: "なのか", meaning: "tanggal 7" },
  { kanji: "八日", reading: "ようか", meaning: "tanggal 8" },
  { kanji: "九日", reading: "ここのか", meaning: "tanggal 9" },
  { kanji: "十日", reading: "とおか", meaning: "tanggal 10" },
  { kanji: "十四日", reading: "じゅうよっか", meaning: "tanggal 14" },
  { kanji: "二十日", reading: "はつか", meaning: "tanggal 20" },
  { kanji: "二十四日", reading: "にじゅうよっか", meaning: "tanggal 24" },

  // --- Hari dalam seminggu ---
  { kanji: "月曜日", reading: "げつようび", meaning: "hari Senin" },
  { kanji: "火曜日", reading: "かようび", meaning: "hari Selasa" },
  { kanji: "水曜日", reading: "すいようび", meaning: "hari Rabu" },
  { kanji: "木曜日", reading: "もくようび", meaning: "hari Kamis" },
  { kanji: "金曜日", reading: "きんようび", meaning: "hari Jumat" },
  { kanji: "土曜日", reading: "どようび", meaning: "hari Sabtu" },
  { kanji: "日曜日", reading: "にちようび", meaning: "hari Minggu" },

  // --- Hubungan manusia ---
  { kanji: "友達", reading: "ともだち", meaning: "teman" },
  { kanji: "家族", reading: "かぞく", meaning: "keluarga" },
  { kanji: "兄弟", reading: "きょうだい", meaning: "saudara (laki-laki / kakak-beradik)" },
  { kanji: "姉妹", reading: "しまい", meaning: "saudara perempuan" },
  { kanji: "父", reading: "ちち", meaning: "ayah (sendiri)" },
  { kanji: "母", reading: "はは", meaning: "ibu (sendiri)" },
  { kanji: "父親", reading: "ちちおや", meaning: "ayah" },
  { kanji: "母親", reading: "ははおや", meaning: "ibu" },
  { kanji: "兄", reading: "あに", meaning: "kakak laki-laki" },
  { kanji: "弟", reading: "おとうと", meaning: "adik laki-laki" },
  { kanji: "姉", reading: "あね", meaning: "kakak perempuan" },
  { kanji: "妹", reading: "いもうと", meaning: "adik perempuan" },
  { kanji: "先生", reading: "せんせい", meaning: "guru / pengajar" },
  { kanji: "学生", reading: "がくせい", meaning: "pelajar / mahasiswa" },
  { kanji: "子供", reading: "こども", meaning: "anak" },
  { kanji: "赤ちゃん", reading: "あかちゃん", meaning: "bayi" },
  { kanji: "男", reading: "おとこ", meaning: "laki-laki" },
  { kanji: "女", reading: "おんな", meaning: "perempuan" },
   { kanji: "人", reading: "ひと", meaning: "orang" },

   // --- Sifat (Adjective) — Kanji X Hiragana Vol 3 ---
   { kanji: "新しい", reading: "あたらしい", meaning: "baru" },
   { kanji: "古い", reading: "ふるい", meaning: "lama / usang" },
   { kanji: "長い", reading: "ながい", meaning: "panjang" },
   { kanji: "高い", reading: "たかい", meaning: "tinggi / mahal" },
   { kanji: "安い", reading: "やすい", meaning: "murah" },
   { kanji: "白い", reading: "しろい", meaning: "putih" },
   { kanji: "早い", reading: "はやい", meaning: "cepat" },
   { kanji: "多い", reading: "おおい", meaning: "banyak" },
   { kanji: "少ない", reading: "すくない", meaning: "sedikit" },
   { kanji: "小さい", reading: "ちいさい", meaning: "kecil" },
   { kanji: "大きい", reading: "おおきい", meaning: "besar" },
   { kanji: "元", reading: "もと", meaning: "asal / awal / dasar" },
   { kanji: "気", reading: "いき", meaning: "napas / udara" },

   // --- Kata Kerja (Verb) — Kanji X Hiragana Vol 3 ---
   { kanji: "行く", reading: "いく", meaning: "pergi" },
   { kanji: "来る", reading: "くる", meaning: "datang" },
   { kanji: "出る", reading: "でる", meaning: "keluar" },
   { kanji: "食べる", reading: "たべる", meaning: "makan" },
   { kanji: "飲む", reading: "のむ", meaning: "minum" },
   { kanji: "見る", reading: "みる", meaning: "melihat" },
   { kanji: "聞く", reading: "きく", meaning: "mendengar / bertanya" },
   { kanji: "読む", reading: "よむ", meaning: "membaca" },
   { kanji: "分ける", reading: "わける", meaning: "membagi" },
   { kanji: "買う", reading: "かう", meaning: "membeli" },
   { kanji: "話す", reading: "はなす", meaning: "berbicara" },
   { kanji: "書く", reading: "かく", meaning: "menulis" },
   { kanji: "会う", reading: "あう", meaning: "bertemu" },
   { kanji: "言う", reading: "いう", meaning: "berkata" },
   { kanji: "生きる", reading: "いきる", meaning: "hidup" },
   { kanji: "立つ", reading: "たつ", meaning: "berdiri" },
   { kanji: "語る", reading: "かたる", meaning: "bercerita" },
   { kanji: "学ぶ", reading: "まなぶ", meaning: "belajar" },
   { kanji: "入る", reading: "はいる", meaning: "masuk" },
   { kanji: "休む", reading: "やすむ", meaning: "beristirahat" },

   // --- Compounds (Kotak 3) — Tahap 2 (98 entries) ---
   // Sifat compounds
   { kanji: "新聞", reading: "しんぶん", meaning: "koran" },
   { kanji: "新年", reading: "しんねん", meaning: "tahun baru" },
   { kanji: "新しい", reading: "あたらしい", meaning: "baru" },
   { kanji: "新潟", reading: "にいがた", meaning: "Niigata (nama daerah)" },
   { kanji: "古本", reading: "ふるほん", meaning: "buku bekas" },
   { kanji: "古い", reading: "ふるい", meaning: "lama / usang" },
   { kanji: "社長", reading: "しゃちょう", meaning: "direktur" },
   { kanji: "店長", reading: "てんちょう", meaning: "kepala toko" },
   { kanji: "長い", reading: "ながい", meaning: "panjang" },
   { kanji: "高校", reading: "こうこう", meaning: "SMA" },
   { kanji: "高い", reading: "たかい", meaning: "tinggi / mahal" },
   { kanji: "安心", reading: "あんしん", meaning: "tenang / lega" },
   { kanji: "安全", reading: "あんぜん", meaning: "aman" },
   { kanji: "安い", reading: "やすい", meaning: "murah" },
   { kanji: "白い", reading: "しろい", meaning: "putih" },
   { kanji: "面白い", reading: "おもしろい", meaning: "menarik / lucu" },
   { kanji: "早い", reading: "はやい", meaning: "cepat / awal" },
   { kanji: "早く", reading: "はやく", meaning: "dengan cepat / lebih awal" },
   { kanji: "多分", reading: "たぶん", meaning: "mungkin" },
   { kanji: "多い", reading: "おおい", meaning: "banyak" },
   { kanji: "少ない", reading: "すくない", meaning: "sedikit" },
   { kanji: "少し", reading: "すこし", meaning: "sedikit" },
   { kanji: "小さい", reading: "ちいさい", meaning: "kecil" },
   { kanji: "小学校", reading: "しょうがっこう", meaning: "Sekolah Dasar (SD)" },
   { kanji: "小麦", reading: "こむぎ", meaning: "gandum" },
   { kanji: "小川", reading: "おがわ", meaning: "sungai kecil" },
   { kanji: "大学", reading: "だいがく", meaning: "universitas / perguruan tinggi" },
   { kanji: "大切", reading: "たいせつ", meaning: "penting / berharga" },
   { kanji: "大きい", reading: "おおきい", meaning: "besar" },
   { kanji: "元日", reading: "がんじつ", meaning: "hari tahun baru (1 Januari)" },
   { kanji: "元気", reading: "げんき", meaning: "sehat / bersemangat" },
   { kanji: "気をつける", reading: "きをつける", meaning: "berhati-hati" },
   { kanji: "気がつく", reading: "きがつく", meaning: "menyadari" },
   // Verba compounds
   { kanji: "行く", reading: "いく", meaning: "pergi" },
   { kanji: "行う", reading: "おこなう", meaning: "melaksanakan / melakukan" },
   { kanji: "銀行", reading: "ぎんこう", meaning: "bank" },
   { kanji: "旅行", reading: "りょこう", meaning: "jalan-jalan / liburan" },
   { kanji: "来る", reading: "くる", meaning: "datang" },
   { kanji: "来月", reading: "らいげつ", meaning: "bulan depan" },
   { kanji: "来年", reading: "らいねん", meaning: "tahun depan" },
   { kanji: "来ない", reading: "こない", meaning: "tidak datang" },
   { kanji: "出る", reading: "でる", meaning: "keluar" },
   { kanji: "出す", reading: "だす", meaning: "mengeluarkan" },
   { kanji: "出発", reading: "しゅっぱつ", meaning: "keberangkatan" },
   { kanji: "出口", reading: "でぐち", meaning: "pintu keluar" },
   { kanji: "食べる", reading: "たべる", meaning: "makan" },
   { kanji: "食堂", reading: "しょくどう", meaning: "kantin" },
   { kanji: "食事", reading: "しょくじ", meaning: "makan / santapan" },
   { kanji: "断食", reading: "だんじき", meaning: "puasa" },
   { kanji: "飲む", reading: "のむ", meaning: "minum" },
   { kanji: "飲食", reading: "いんしょく", meaning: "makan dan minum" },
   { kanji: "見る", reading: "みる", meaning: "melihat" },
   { kanji: "花見", reading: "はなみ", meaning: "melihat bunga (sakura)" },
   { kanji: "見学", reading: "けんがく", meaning: "studi banding / observasi" },
   { kanji: "聞く", reading: "きく", meaning: "mendengar / bertanya" },
   { kanji: "新聞", reading: "しんぶん", meaning: "koran" },
   { kanji: "聞こえる", reading: "きこえる", meaning: "terdengar" },
   { kanji: "読む", reading: "よむ", meaning: "membaca" },
   { kanji: "読み物", reading: "よみもの", meaning: "bahan bacaan" },
   { kanji: "読書", reading: "どくしょ", meaning: "membaca buku" },
   { kanji: "分ける", reading: "わける", meaning: "membagi" },
   { kanji: "五分", reading: "ごふん", meaning: "5 menit" },
   { kanji: "三分", reading: "さんぷん", meaning: "3 menit" },
   { kanji: "六分", reading: "ろっぷん", meaning: "6 menit" },
   { kanji: "買う", reading: "かう", meaning: "membeli" },
   { kanji: "売買", reading: "ばいばい", meaning: "jual beli" },
   { kanji: "話す", reading: "はなす", meaning: "berbicara" },
   { kanji: "電話", reading: "でんわ", meaning: "telepon" },
   { kanji: "会話", reading: "かいわ", meaning: "percakapan" },
   { kanji: "書く", reading: "かく", meaning: "menulis" },
   { kanji: "図書館", reading: "としょかん", meaning: "perpustakaan" },
   { kanji: "辞書", reading: "じしょ", meaning: "kamus" },
   { kanji: "会う", reading: "あう", meaning: "bertemu" },
   { kanji: "会社", reading: "かいしゃ", meaning: "perusahaan" },
   { kanji: "会話", reading: "かいわ", meaning: "percakapan" },
   { kanji: "言う", reading: "いう", meaning: "berkata" },
   { kanji: "言葉", reading: "ことば", meaning: "kata / bahasa" },
   { kanji: "生きる", reading: "いきる", meaning: "hidup" },
   { kanji: "学生", reading: "がくせい", meaning: "siswa / mahasiswa" },
   { kanji: "先生", reading: "せんせい", meaning: "guru / pengajar" },
   { kanji: "生肉", reading: "なまにく", meaning: "daging mentah" },
   { kanji: "立つ", reading: "たつ", meaning: "berdiri" },
   { kanji: "起立", reading: "きりつ", meaning: "berdiri (aba-aba)" },
   { kanji: "語る", reading: "かたる", meaning: "bercerita" },
   { kanji: "日本語", reading: "にほんご", meaning: "bahasa Jepang" },
   { kanji: "英語", reading: "えいご", meaning: "bahasa Inggris" },
   { kanji: "学ぶ", reading: "まなぶ", meaning: "belajar" },
   { kanji: "大学", reading: "だいがく", meaning: "universitas / perguruan tinggi" },
   { kanji: "学校", reading: "がっこう", meaning: "sekolah" },
   { kanji: "学院", reading: "がくいん", meaning: "akademi / sekolah" },
   { kanji: "入る", reading: "はいる", meaning: "masuk" },
   { kanji: "入門", reading: "にゅうもん", meaning: "pengantar / pengenalan dasar" },
   { kanji: "入口", reading: "いりぐち", meaning: "pintu masuk" },
   { kanji: "入学", reading: "にゅうがく", meaning: "masuk sekolah / pendaftaran" },
   { kanji: "休む", reading: "やすむ", meaning: "beristirahat" },
   { kanji: "休日", reading: "きょうじつ", meaning: "hari libur" },
   { kanji: "夏休み", reading: "なつやすみ", meaning: "libur musim panas" },
   { kanji: "昼休み", reading: "ひるやすみ", meaning: "istirahat siang" },
];
