// Deck: kanji angka + hubungan manusia
// Cara menambah: salin satu baris { kanji, reading, meaning },
const cards = [
  // --- Angka dasar ---
  { kanji: "一", reading: "いち", meaning: "satu" },
  { kanji: "二", reading: "に", meaning: "dua" },
  { kanji: "三", reading: "さん", meaning: "tiga" },
  { kanji: "四", reading: "よん・し", meaning: "empat" },
  { kanji: "五", reading: "ご", meaning: "lima" },
  { kanji: "六", reading: "ろく", meaning: "enam" },
  { kanji: "七", reading: "なな・しち", meaning: "tujuh" },
  { kanji: "八", reading: "はち", meaning: "delapan" },
  { kanji: "九", reading: "きゅう・く", meaning: "sembilan" },
  { kanji: "十", reading: "じゅう", meaning: "sepuluh" },
  { kanji: "百", reading: "ひゃく", meaning: "seratus" },
  { kanji: "千", reading: "せん", meaning: "seribu" },
  { kanji: "万", reading: "まん", meaning: "sepuluh ribu" },
  { kanji: "円", reading: "えん", meaning: "yen (mata uang Jepang)" },

  // --- Tanggal ---
  { kanji: "一日", reading: "ついたち", meaning: "tanggal 1" },
  { kanji: "二日", reading: "ふつか", meaning: "tanggal 2" },
  { kanji: "三日", reading: "みっか", meaning: "tanggal 3" },
  { kanji: "四日", reading: "よっか", meaning: "tanggal 4" },
  { kanji: "五日", reading: "いつか", meaning: "tanggal 5" },
  { kanji: "六日", reading: "むいか", meaning: "tanggal 6" },
  { kanji: "七日", reading: "なのか", meaning: "tanggal 7" },
  { kanji: "八日", reading: "ようか", meaning: "tanggal 8" },
  { kanji: "九日", reading: "ここのか", meaning: "tanggal 9" },
  { kanji: "十日", reading: "とおか", meaning: "tanggal 10" },
  { kanji: "十四日", reading: "じゅうよっか", meaning: "tanggal 14" },
  { kanji: "二十日", reading: "はつか", meaning: "tanggal 20" },
  { kanji: "二十四日", reading: "にじゅうよっか", meaning: "tanggal 24" },

  // --- Hari dalam seminggu ---
  { kanji: "月曜日", reading: "げつようび", meaning: "hari Senin" },
  { kanji: "火曜日", reading: "かようび", meaning: "hari Selasa" },
  { kanji: "水曜日", reading: "すいようび", meaning: "hari Rabu" },
  { kanji: "木曜日", reading: "もくようび", meaning: "hari Kamis" },
  { kanji: "金曜日", reading: "きんようび", meaning: "hari Jumat" },
  { kanji: "土曜日", reading: "どようび", meaning: "hari Sabtu" },
  { kanji: "日曜日", reading: "にちようび", meaning: "hari Minggu" },

  // --- Hubungan manusia ---
  { kanji: "友達", reading: "ともだち", meaning: "teman" },
  { kanji: "家族", reading: "かぞく", meaning: "keluarga" },
  { kanji: "兄弟", reading: "きょうだい", meaning: "saudara (laki-laki / kakak-beradik)" },
  { kanji: "姉妹", reading: "しまい", meaning: "saudara perempuan" },
  { kanji: "父", reading: "ちち", meaning: "ayah (sendiri)" },
  { kanji: "母", reading: "はは", meaning: "ibu (sendiri)" },
  { kanji: "父親", reading: "ちちおや", meaning: "ayah" },
  { kanji: "母親", reading: "ははおや", meaning: "ibu" },
  { kanji: "兄", reading: "あに", meaning: "kakak laki-laki" },
  { kanji: "弟", reading: "おとうと", meaning: "adik laki-laki" },
  { kanji: "姉", reading: "あね", meaning: "kakak perempuan" },
  { kanji: "妹", reading: "いもうと", meaning: "adik perempuan" },
  { kanji: "先生", reading: "せんせい", meaning: "guru / pengajar" },
  { kanji: "学生", reading: "がくせい", meaning: "pelajar / mahasiswa" },
  { kanji: "子供", reading: "こども", meaning: "anak" },
  { kanji: "赤ちゃん", reading: "あかちゃん", meaning: "bayi" },
  { kanji: "男", reading: "おとこ", meaning: "laki-laki" },
  { kanji: "女", reading: "おんな", meaning: "perempuan" },
  { kanji: "人", reading: "ひと", meaning: "orang" },
];
