// Deck: kanji angka + hubungan manusia
// Cara menambah: salin satu baris { kanji, reading, meaning },
const cards = [
  // --- Angka dasar ---
  { kanji: "一", reading: "いち", meaning: "satu" },
  { kanji: "二", reading: "に", meaning: "dua" },
  { kanji: "三", reading: "さん", meaning: "tiga" },
  { kanji: "四", reading: "よん・し", meaning: "empat" },
  { kanji: "五", reading: "ご", meaning: "lima" },
  { kanji: "六", reading: "ろく", meaning: "enam" },
  { kanji: "七", reading: "なな・しち", meaning: "tujuh" },
  { kanji: "八", reading: "はち", meaning: "delapan" },
  { kanji: "九", reading: "きゅう・く", meaning: "sembilan" },
  { kanji: "十", reading: "じゅう", meaning: "sepuluh" },
  { kanji: "百", reading: "ひゃく", meaning: "seratus" },
  { kanji: "千", reading: "せん", meaning: "seribu" },
  { kanji: "万", reading: "まん", meaning: "sepuluh ribu" },
  { kanji: "円", reading: "えん", meaning: "yen (mata uang Jepang)" },

  // --- Tanggal ---
  { kanji: "一日", reading: "ついたち", meaning: "tanggal 1" },
  { kanji: "二日", reading: "ふつか", meaning: "tanggal 2" },
  { kanji: "三日", reading: "みっか", meaning: "tanggal 3" },
  { kanji: "四日", reading: "よっか", meaning: "tanggal 4" },
  { kanji: "五日", reading: "いつか", meaning: "tanggal 5" },
  { kanji: "六日", reading: "むいか", meaning: "tanggal 6" },
  { kanji: "七日", reading: "なのか", meaning: "tanggal 7" },
  { kanji: "八日", reading: "ようか", meaning: "tanggal 8" },
  { kanji: "九日", reading: "ここのか", meaning: "tanggal 9" },
  { kanji: "十日", reading: "とおか", meaning: "tanggal 10" },
  { kanji: "十四日", reading: "じゅうよっか", meaning: "tanggal 14" },
  { kanji: "二十日", reading: "はつか", meaning: "tanggal 20" },
  { kanji: "二十四日", reading: "にじゅうよっか", meaning: "tanggal 24" },

  // --- Hari dalam seminggu ---
  { kanji: "月曜日", reading: "げつようび", meaning: "hari Senin" },
  { kanji: "火曜日", reading: "かようび", meaning: "hari Selasa" },
  { kanji: "水曜日", reading: "すいようび", meaning: "hari Rabu" },
  { kanji: "木曜日", reading: "もくようび", meaning: "hari Kamis" },
  { kanji: "金曜日", reading: "きんようび", meaning: "hari Jumat" },
  { kanji: "土曜日", reading: "どようび", meaning: "hari Sabtu" },
  { kanji: "日曜日", reading: "にちようび", meaning: "hari Minggu" },

  // --- Hubungan manusia ---
  { kanji: "友達", reading: "ともだち", meaning: "teman" },
  { kanji: "家族", reading: "かぞく", meaning: "keluarga" },
  { kanji: "兄弟", reading: "きょうだい", meaning: "saudara (laki-laki / kakak-beradik)" },
  { kanji: "姉妹", reading: "しまい", meaning: "saudara perempuan" },
  { kanji: "父", reading: "ちち", meaning: "ayah (sendiri)" },
  { kanji: "母", reading: "はは", meaning: "ibu (sendiri)" },
  { kanji: "父親", reading: "ちちおや", meaning: "ayah" },
  { kanji: "母親", reading: "ははおや", meaning: "ibu" },
  { kanji: "兄", reading: "あに", meaning: "kakak laki-laki" },
  { kanji: "弟", reading: "おとうと", meaning: "adik laki-laki" },
  { kanji: "姉", reading: "あね", meaning: "kakak perempuan" },
  { kanji: "妹", reading: "いもうと", meaning: "adik perempuan" },
  { kanji: "先生", reading: "せんせい", meaning: "guru / pengajar" },
  { kanji: "学生", reading: "がくせい", meaning: "pelajar / mahasiswa" },
  { kanji: "子供", reading: "こども", meaning: "anak" },
  { kanji: "赤ちゃん", reading: "あかちゃん", meaning: "bayi" },
  { kanji: "男", reading: "おとこ", meaning: "laki-laki" },
  { kanji: "女", reading: "おんな", meaning: "perempuan" },
   { kanji: "人", reading: "ひと", meaning: "orang" },

   // --- Sifat (Adjective) — Kanji X Hiragana Vol 3 ---
   { kanji: "新しい", reading: "あたらしい", meaning: "baru" },
   { kanji: "古い", reading: "ふるい", meaning: "lama / usang" },
   { kanji: "長い", reading: "ながい", meaning: "panjang" },
   { kanji: "高い", reading: "たかい", meaning: "tinggi / mahal" },
   { kanji: "安い", reading: "やすい", meaning: "murah" },
   { kanji: "白い", reading: "しろい", meaning: "putih" },
   { kanji: "早い", reading: "はやい", meaning: "cepat" },
   { kanji: "多い", reading: "おおい", meaning: "banyak" },
   { kanji: "少ない", reading: "すくない", meaning: "sedikit" },
   { kanji: "小さい", reading: "ちいさい", meaning: "kecil" },
   { kanji: "大きい", reading: "おおきい", meaning: "besar" },
   { kanji: "元", reading: "もと", meaning: "asal / awal / dasar" },
   { kanji: "気", reading: "いき", meaning: "napas / udara" },

   // --- Kata Kerja (Verb) — Kanji X Hiragana Vol 3 ---
   { kanji: "行く", reading: "いく", meaning: "pergi" },
   { kanji: "来る", reading: "くる", meaning: "datang" },
   { kanji: "出る", reading: "でる", meaning: "keluar" },
   { kanji: "食べる", reading: "たべる", meaning: "makan" },
   { kanji: "飲む", reading: "のむ", meaning: "minum" },
   { kanji: "見る", reading: "みる", meaning: "melihat" },
   { kanji: "聞く", reading: "きく", meaning: "mendengar / bertanya" },
   { kanji: "読む", reading: "よむ", meaning: "membaca" },
   { kanji: "分ける", reading: "わける", meaning: "membagi" },
   { kanji: "買う", reading: "かう", meaning: "membeli" },
   { kanji: "話す", reading: "はなす", meaning: "berbicara" },
   { kanji: "書く", reading: "かく", meaning: "menulis" },
   { kanji: "会う", reading: "あう", meaning: "bertemu" },
   { kanji: "言う", reading: "いう", meaning: "berkata" },
   { kanji: "生きる", reading: "いきる", meaning: "hidup" },
   { kanji: "立つ", reading: "たつ", meaning: "berdiri" },
   { kanji: "語る", reading: "かたる", meaning: "bercerita" },
   { kanji: "学ぶ", reading: "まなぶ", meaning: "belajar" },
   { kanji: "入る", reading: "はいる", meaning: "masuk" },
   { kanji: "休む", reading: "やすむ", meaning: "beristirahat" },

   // --- Compounds (Kotak 3) — Tahap 2 (98 entries) ---
   // Sifat compounds
   { kanji: "新聞", reading: "しんぶん", meaning: "koran" },
   { kanji: "新年", reading: "しんねん", meaning: "tahun baru" },
   { kanji: "新しい", reading: "あたらしい", meaning: "baru" },
   { kanji: "新潟", reading: "にいがた", meaning: "Niigata (nama daerah)" },
   { kanji: "古本", reading: "ふるほん", meaning: "buku bekas" },
   { kanji: "古い", reading: "ふるい", meaning: "lama / usang" },
   { kanji: "社長", reading: "しゃちょう", meaning: "direktur" },
   { kanji: "店長", reading: "てんちょう", meaning: "kepala toko" },
   { kanji: "長い", reading: "ながい", meaning: "panjang" },
   { kanji: "高校", reading: "こうこう", meaning: "SMA" },
   { kanji: "高い", reading: "たかい", meaning: "tinggi / mahal" },
   { kanji: "安心", reading: "あんしん", meaning: "tenang / lega" },
   { kanji: "安全", reading: "あんぜん", meaning: "aman" },
   { kanji: "安い", reading: "やすい", meaning: "murah" },
   { kanji: "白い", reading: "しろい", meaning: "putih" },
   { kanji: "面白い", reading: "おもしろい", meaning: "menarik / lucu" },
   { kanji: "早い", reading: "はやい", meaning: "cepat / awal" },
   { kanji: "早く", reading: "はやく", meaning: "dengan cepat / lebih awal" },
   { kanji: "多分", reading: "たぶん", meaning: "mungkin" },
   { kanji: "多い", reading: "おおい", meaning: "banyak" },
   { kanji: "少ない", reading: "すくない", meaning: "sedikit" },
   { kanji: "少し", reading: "すこし", meaning: "sedikit" },
   { kanji: "小さい", reading: "ちいさい", meaning: "kecil" },
   { kanji: "小学校", reading: "しょうがっこう", meaning: "Sekolah Dasar (SD)" },
   { kanji: "小麦", reading: "こむぎ", meaning: "gandum" },
   { kanji: "小川", reading: "おがわ", meaning: "sungai kecil" },
   { kanji: "大学", reading: "だいがく", meaning: "universitas / perguruan tinggi" },
   { kanji: "大切", reading: "たいせつ", meaning: "penting / berharga" },
   { kanji: "大きい", reading: "おおきい", meaning: "besar" },
   { kanji: "元日", reading: "がんじつ", meaning: "hari tahun baru (1 Januari)" },
   { kanji: "元気", reading: "げんき", meaning: "sehat / bersemangat" },
   { kanji: "気をつける", reading: "きをつける", meaning: "berhati-hati" },
   { kanji: "気がつく", reading: "きがつく", meaning: "menyadari" },
   // Verba compounds
   { kanji: "行く", reading: "いく", meaning: "pergi" },
   { kanji: "行う", reading: "おこなう", meaning: "melaksanakan / melakukan" },
   { kanji: "銀行", reading: "ぎんこう", meaning: "bank" },
   { kanji: "旅行", reading: "りょこう", meaning: "jalan-jalan / liburan" },
   { kanji: "来る", reading: "くる", meaning: "datang" },
   { kanji: "来月", reading: "らいげつ", meaning: "bulan depan" },
   { kanji: "来年", reading: "らいねん", meaning: "tahun depan" },
   { kanji: "来ない", reading: "こない", meaning: "tidak datang" },
   { kanji: "出る", reading: "でる", meaning: "keluar" },
   { kanji: "出す", reading: "だす", meaning: "mengeluarkan" },
   { kanji: "出発", reading: "しゅっぱつ", meaning: "keberangkatan" },
   { kanji: "出口", reading: "でぐち", meaning: "pintu keluar" },
   { kanji: "食べる", reading: "たべる", meaning: "makan" },
   { kanji: "食堂", reading: "しょくどう", meaning: "kantin" },
   { kanji: "食事", reading: "しょくじ", meaning: "makan / santapan" },
   { kanji: "断食", reading: "だんじき", meaning: "puasa" },
   { kanji: "飲む", reading: "のむ", meaning: "minum" },
   { kanji: "飲食", reading: "いんしょく", meaning: "makan dan minum" },
   { kanji: "見る", reading: "みる", meaning: "melihat" },
   { kanji: "花見", reading: "はなみ", meaning: "melihat bunga (sakura)" },
   { kanji: "見学", reading: "けんがく", meaning: "studi banding / observasi" },
   { kanji: "聞く", reading: "きく", meaning: "mendengar / bertanya" },
   { kanji: "新聞", reading: "しんぶん", meaning: "koran" },
   { kanji: "聞こえる", reading: "きこえる", meaning: "terdengar" },
   { kanji: "読む", reading: "よむ", meaning: "membaca" },
   { kanji: "読み物", reading: "よみもの", meaning: "bahan bacaan" },
   { kanji: "読書", reading: "どくしょ", meaning: "membaca buku" },
   { kanji: "分ける", reading: "わける", meaning: "membagi" },
   { kanji: "五分", reading: "ごふん", meaning: "5 menit" },
   { kanji: "三分", reading: "さんぷん", meaning: "3 menit" },
   { kanji: "六分", reading: "ろっぷん", meaning: "6 menit" },
   { kanji: "買う", reading: "かう", meaning: "membeli" },
   { kanji: "売買", reading: "ばいばい", meaning: "jual beli" },
   { kanji: "話す", reading: "はなす", meaning: "berbicara" },
   { kanji: "電話", reading: "でんわ", meaning: "telepon" },
   { kanji: "会話", reading: "かいわ", meaning: "percakapan" },
   { kanji: "書く", reading: "かく", meaning: "menulis" },
   { kanji: "図書館", reading: "としょかん", meaning: "perpustakaan" },
   { kanji: "辞書", reading: "じしょ", meaning: "kamus" },
   { kanji: "会う", reading: "あう", meaning: "bertemu" },
   { kanji: "会社", reading: "かいしゃ", meaning: "perusahaan" },
   { kanji: "会話", reading: "かいわ", meaning: "percakapan" },
   { kanji: "言う", reading: "いう", meaning: "berkata" },
   { kanji: "言葉", reading: "ことば", meaning: "kata / bahasa" },
   { kanji: "生きる", reading: "いきる", meaning: "hidup" },
   { kanji: "学生", reading: "がくせい", meaning: "siswa / mahasiswa" },
   { kanji: "先生", reading: "せんせい", meaning: "guru / pengajar" },
   { kanji: "生肉", reading: "なまにく", meaning: "daging mentah" },
   { kanji: "立つ", reading: "たつ", meaning: "berdiri" },
   { kanji: "起立", reading: "きりつ", meaning: "berdiri (aba-aba)" },
   { kanji: "語る", reading: "かたる", meaning: "bercerita" },
   { kanji: "日本語", reading: "にほんご", meaning: "bahasa Jepang" },
   { kanji: "英語", reading: "えいご", meaning: "bahasa Inggris" },
   { kanji: "学ぶ", reading: "まなぶ", meaning: "belajar" },
   { kanji: "大学", reading: "だいがく", meaning: "universitas / perguruan tinggi" },
   { kanji: "学校", reading: "がっこう", meaning: "sekolah" },
   { kanji: "学院", reading: "がくいん", meaning: "akademi / sekolah" },
   { kanji: "入る", reading: "はいる", meaning: "masuk" },
   { kanji: "入門", reading: "にゅうもん", meaning: "pengantar / pengenalan dasar" },
   { kanji: "入口", reading: "いりぐち", meaning: "pintu masuk" },
   { kanji: "入学", reading: "にゅうがく", meaning: "masuk sekolah / pendaftaran" },
   { kanji: "休む", reading: "やすむ", meaning: "beristirahat" },
   { kanji: "休日", reading: "きょうじつ", meaning: "hari libur" },
   { kanji: "夏休み", reading: "なつやすみ", meaning: "libur musim panas" },
   { kanji: "昼休み", reading: "ひるやすみ", meaning: "istirahat siang" },
  // --- Bab 5: Waktu (Kanji 5-7 AYAH - main words) ---
  { kanji: "日", reading: "ひ", meaning: "hari" },
  { kanji: "月", reading: "つき", meaning: "bulan" },
  { kanji: "火", reading: "ひ", meaning: "api" },
  { kanji: "水", reading: "みず", meaning: "air" },
  { kanji: "木", reading: "き", meaning: "pohon" },
  { kanji: "金", reading: "かね", meaning: "emas / uang" },
  { kanji: "土", reading: "つち", meaning: "tanah" },
  { kanji: "毎", reading: "まい", meaning: "setiap" },
  { kanji: "午", reading: "ご", meaning: "siang" },
  { kanji: "時", reading: "とき", meaning: "waktu / jam" },
  { kanji: "間", reading: "あいだ", meaning: "waktu / antara" },
  { kanji: "年", reading: "とし", meaning: "tahun" },
  { kanji: "今", reading: "いま", meaning: "sekarang" },
  { kanji: "週", reading: "しゅう", meaning: "~ minggu" },
  { kanji: "半", reading: "なかば", meaning: "setengah" },
  // --- Bab 5: Waktu (Kanji 5-7 ANAK - compounds) ---
  { kanji: "日曜日", reading: "にちようび", meaning: "hari Minggu" },
  { kanji: "五日", reading: "いつか", meaning: "tanggal 5 / 5 hari" },
  { kanji: "日本", reading: "にほん", meaning: "Jepang" },
  { kanji: "休日", reading: "きゅうじつ", meaning: "hari libur" },
  { kanji: "月曜日", reading: "げつようび", meaning: "hari Senin" },
  { kanji: "四月", reading: "しがつ", meaning: "bulan April" },
  { kanji: "六か月", reading: "ろっかけつ", meaning: "6 bulan" },
  { kanji: "毎月", reading: "まいつき", meaning: "setiap bulan" },
  { kanji: "火曜日", reading: "かようび", meaning: "hari Selasa" },
  { kanji: "火山", reading: "かざん", meaning: "gunung berapi" },
  { kanji: "火事", reading: "かじ", meaning: "kebakaran" },
  { kanji: "花火", reading: "はなび", meaning: "kembang api" },
  { kanji: "水曜日", reading: "すいようび", meaning: "hari Rabu" },
  { kanji: "水道", reading: "すいどう", meaning: "saluran air / PDAM" },
  { kanji: "水冷", reading: "すいれい", meaning: "pendingin air" },
  { kanji: "鼻水", reading: "はなみず", meaning: "ingus" },
  { kanji: "木曜日", reading: "もくようび", meaning: "hari Kamis" },
  { kanji: "大木", reading: "たいぼく", meaning: "pohon besar" },
  { kanji: "金曜日", reading: "きんようび", meaning: "hari Jumat" },
  { kanji: "お金", reading: "おかね", meaning: "uang" },
  { kanji: "現金", reading: "げんきん", meaning: "uang tunai" },
  { kanji: "土曜日", reading: "どようび", meaning: "hari Sabtu" },
  { kanji: "土木", reading: "どぼく", meaning: "teknik sipil / pekerjaan umum" },
  { kanji: "毎晩", reading: "まいばん", meaning: "setiap malam" },
  { kanji: "毎週", reading: "まいしゅう", meaning: "setiap minggu" },
  { kanji: "毎朝", reading: "まいあさ", meaning: "setiap pagi" },
  { kanji: "毎に", reading: "ごとに", meaning: "setiap / per" },
  { kanji: "午前", reading: "ごぜん", meaning: "AM (pagi/sebelum siang)" },
  { kanji: "午後", reading: "ごご", meaning: "PM (siang/setelah siang)" },
  { kanji: "時々", reading: "ときどき", meaning: "kadang-kadang" },
  { kanji: "時間", reading: "じかん", meaning: "waktu / jam" },
  { kanji: "何時", reading: "なんじ", meaning: "jam berapa" },
  { kanji: "七時", reading: "しちじ", meaning: "jam 7" },
  { kanji: "時間", reading: "じかん", meaning: "waktu / jam" },
  { kanji: "人間", reading: "にんげん", meaning: "manusia" },
  { kanji: "間違い", reading: "まちがい", meaning: "kesalahan / kekeliruan" },
  { kanji: "今年", reading: "ことし", meaning: "tahun ini" },
  { kanji: "毎年", reading: "まいとし / まいねん", meaning: "setiap tahun" },
  { kanji: "来年", reading: "らいねん", meaning: "tahun depan" },
  { kanji: "去年", reading: "きょねん", meaning: "tahun lalu" },
  { kanji: "今週", reading: "こんしゅう", meaning: "minggu ini" },
  { kanji: "今年", reading: "ことし", meaning: "tahun ini" },
  { kanji: "今朝", reading: "けさ", meaning: "tadi pagi" },
  { kanji: "来週", reading: "らいしゅう", meaning: "minggu depan" },
  { kanji: "先週", reading: "せんしゅう", meaning: "minggu lalu" },
  { kanji: "週末", reading: "しゅうまつ", meaning: "akhir minggu (weekend)" },
  { kanji: "毎週", reading: "まいしゅう", meaning: "setiap minggu" },
  { kanji: "四時半", reading: "よじはん", meaning: "jam 4 lewat setengah (4.30)" },
  { kanji: "半ば", reading: "なかば", meaning: "pertengahan" },
  // --- Bab 6: Arah (Kanji 5-7 AYAH - main words) ---
  { kanji: "先", reading: "さき", meaning: "duluan" },
  { kanji: "後", reading: "うしろ", meaning: "belakang" },
  { kanji: "前", reading: "まえ", meaning: "depan" },
  { kanji: "右", reading: "みぎ", meaning: "kanan" },
  { kanji: "左", reading: "ひだり", meaning: "kiri" },
  { kanji: "上", reading: "うえ", meaning: "atas" },
  { kanji: "下", reading: "した", meaning: "bawah" },
  { kanji: "西", reading: "にし", meaning: "barat" },
  { kanji: "東", reading: "ひがし", meaning: "timur" },
  { kanji: "北", reading: "きた", meaning: "utara" },
  { kanji: "南", reading: "みなみ", meaning: "selatan" },
  { kanji: "中", reading: "なか", meaning: "dalam" },
  { kanji: "外", reading: "そと", meaning: "luar" },
  // --- Bab 6: Arah (Kanji 5-7 ANAK - compounds) ---
  { kanji: "先週", reading: "せんしゅう", meaning: "minggu lalu" },
  { kanji: "先月", reading: "せんげつ", meaning: "bulan lalu" },
  { kanji: "先に", reading: "さきに", meaning: "duluan / terlebih dahulu" },
  { kanji: "先生", reading: "せんせい", meaning: "guru / pengajar" },
  { kanji: "午後", reading: "ごご", meaning: "PM (siang/sore)" },
  { kanji: "後ろ", reading: "うしろ", meaning: "belakang" },
  { kanji: "後で", reading: "あとで", meaning: "nanti" },
  { kanji: "最後", reading: "さいご", meaning: "terakhir" },
  { kanji: "午前", reading: "ごぜん", meaning: "AM (pagi/sebelum siang)" },
  { kanji: "前後", reading: "ぜんご", meaning: "depan belakang / kurang lebih" },
  { kanji: "名前", reading: "なまえ", meaning: "nama" },
  { kanji: "三年前", reading: "さんねんまえ", meaning: "3 tahun yang lalu" },
  { kanji: "右手", reading: "みぎて", meaning: "tangan kanan" },
  { kanji: "右足", reading: "みぎあし", meaning: "kaki kanan" },
  { kanji: "左手", reading: "ひだりて", meaning: "tangan kiri" },
  { kanji: "左右", reading: "さゆう", meaning: "kiri dan kanan" },
  { kanji: "上げる", reading: "あげる", meaning: "menaikkan" },
  { kanji: "上手な", reading: "じょうずな", meaning: "pandai / mahir" },
  { kanji: "上着", reading: "うわぎ", meaning: "jaket / pakaian luar" },
  { kanji: "上がる", reading: "あがる", meaning: "naik" },
  { kanji: "下げる", reading: "さげる", meaning: "menurunkan" },
  { kanji: "下さい", reading: "ください", meaning: "tolong / silakan" },
  { kanji: "下ろす", reading: "おろす", meaning: "menurunkan / mengambil (uang)" },
  { kanji: "下手な", reading: "へたな", meaning: "tidak pandai / Payah" },
  { kanji: "西口", reading: "にしぐち", meaning: "pintu keluar barat" },
  { kanji: "関西", reading: "かんさい", meaning: "Kansai (wilayah di Jepang)" },
  { kanji: "南西", reading: "なんせい", meaning: "barat daya" },
  { kanji: "北西", reading: "ほくせい", meaning: "barat laut" },
  { kanji: "東口", reading: "ひがしぐち", meaning: "pintu keluar timur" },
  { kanji: "東京", reading: "とうきょう", meaning: "Tokyo" },
  { kanji: "関東", reading: "かんとう", meaning: "Kanto (wilayah di Jepang)" },
  { kanji: "北東", reading: "ほくとう", meaning: "timur laut" },
  { kanji: "北口", reading: "きたぐち", meaning: "pintu keluar utara" },
  { kanji: "北海道", reading: "ほっかいどう", meaning: "Hokkaido" },
  { kanji: "南北", reading: "なんぼく", meaning: "utara dan selatan" },
  { kanji: "南口", reading: "みなみぐち", meaning: "pintu keluar selatan" },
  { kanji: "南東", reading: "なんとう", meaning: "tenggara" },
  { kanji: "中国", reading: "ちゅうごく", meaning: "Cina" },
  { kanji: "中学校", reading: "ちゅうがっこう", meaning: "SMP" },
  { kanji: "外国", reading: "がいこく", meaning: "luar negeri" },
  { kanji: "国外", reading: "こくがい", meaning: "luar negeri" },
  { kanji: "外す", reading: "はずす", meaning: "melepas / mengelakkan" },
  { kanji: "外食", reading: "がいしょく", meaning: "makan di luar" },
  // --- Bab 7: Kata Benda (Kanji 5-7 AYAH - main words) ---
  { kanji: "名", reading: "めい", meaning: "nama" },
  { kanji: "校", reading: "こう", meaning: "sekolah" },
  { kanji: "天", reading: "てん", meaning: "angkasa / langit" },
  { kanji: "電", reading: "でん", meaning: "listrik" },
  { kanji: "車", reading: "くるま", meaning: "mobil / kendaraan" },
  { kanji: "田", reading: "た", meaning: "sawah" },
  { kanji: "門", reading: "もん", meaning: "gerbang" },
  { kanji: "店", reading: "みせ", meaning: "toko" },
  { kanji: "力", reading: "ちから", meaning: "tenaga / kekuatan" },
  { kanji: "口", reading: "くち", meaning: "mulut" },
  { kanji: "耳", reading: "みみ", meaning: "telinga" },
  { kanji: "目", reading: "め", meaning: "mata" },
  { kanji: "手", reading: "て", meaning: "tangan" },
  { kanji: "国", reading: "くに", meaning: "negara" },
  { kanji: "社", reading: "しゃ", meaning: "perusahaan" },
  { kanji: "駅", reading: "えき", meaning: "stasiun" },
  { kanji: "雨", reading: "あめ", meaning: "hujan" },
  { kanji: "道", reading: "みち", meaning: "jalan" },
  { kanji: "山", reading: "やま", meaning: "gunung" },
  { kanji: "空", reading: "そら", meaning: "langit" },
  { kanji: "花", reading: "はな", meaning: "bunga" },
  { kanji: "川", reading: "かわ", meaning: "sungai" },
  { kanji: "牛", reading: "うし", meaning: "sapi" },
  { kanji: "貝", reading: "かい", meaning: "kerang" },
  { kanji: "馬", reading: "うま", meaning: "kuda" },
  { kanji: "魚", reading: "さかな", meaning: "ikan" },
  { kanji: "人", reading: "ひと", meaning: "orang" },
  { kanji: "本", reading: "ほん", meaning: "buku" },
  { kanji: "何", reading: "なに", meaning: "apa" },
  // --- Bab 7: Kata Benda (Kanji 5-7 ANAK - compounds) ---
  { kanji: "名前", reading: "なまえ", meaning: "nama" },
  { kanji: "名札", reading: "なふだ", meaning: "papan nama / tag nama" },
  { kanji: "名字", reading: "みょうじ", meaning: "nama keluarga / nama belakang" },
  { kanji: "有名", reading: "ゆうめい", meaning: "terkenal" },
  { kanji: "学校", reading: "がっこう", meaning: "sekolah" },
  { kanji: "高校", reading: "こうこう", meaning: "SMA" },
  { kanji: "校門", reading: "こうもん", meaning: "gerbang sekolah" },
  { kanji: "校長", reading: "こうちょう", meaning: "kepala sekolah" },
  { kanji: "天気", reading: "てんき", meaning: "cuaca" },
  { kanji: "天地", reading: "てんち", meaning: "langit dan bumi" },
  { kanji: "電気", reading: "でんき", meaning: "listrik / lampu" },
  { kanji: "電車", reading: "でんしゃ", meaning: "kereta listrik" },
  { kanji: "電話", reading: "でんわ", meaning: "telepon" },
  { kanji: "車いす", reading: "くるまいす", meaning: "kursi roda" },
  { kanji: "自動車", reading: "じどうしゃ", meaning: "mobil" },
  { kanji: "自転車", reading: "じてんしゃ", meaning: "sepeda" },
  { kanji: "山田", reading: "やまだ", meaning: "Yamada (nama orang)" },
  { kanji: "田中", reading: "たなか", meaning: "Tanaka (nama orang)" },
  { kanji: "水田", reading: "すいでん", meaning: "sawah tergenang air" },
  { kanji: "専門", reading: "せんもん", meaning: "keahlian / spesialisasi" },
  { kanji: "入門", reading: "にゅうもん", meaning: "pengantar / pengenalan dasar" },
  { kanji: "店員", reading: "てんいん", meaning: "pegawai toko" },
  { kanji: "店長", reading: "てんちょう", meaning: "manajer toko" },
  { kanji: "店", reading: "みせ", meaning: "toko" },
  { kanji: "電力", reading: "でんりょく", meaning: "daya listrik" },
  { kanji: "人力車", reading: "じんりきしゃ", meaning: "jinrikisha / becak tarik manusia" },
  { kanji: "動力", reading: "どうりょく", meaning: "tenaga penggerak / daya" },
  { kanji: "入口", reading: "いりぐち", meaning: "pintu masuk" },
  { kanji: "人口", reading: "じんこう", meaning: "populasi / jumlah penduduk" },
  { kanji: "山口", reading: "やまぐち", meaning: "Yamaguchi (nama tempat/orang)" },
  { kanji: "出口", reading: "でぐち", meaning: "pintu keluar" },
  { kanji: "〜目", reading: "〜め", meaning: "ke- (urutan, contoh: 第 1 目 / 1 つ目)" },
  { kanji: "目的", reading: "もくてき", meaning: "tujuan / maksud" },
  { kanji: "下手な", reading: "へたな", meaning: "tidak pandai / kurang mahir" },
  { kanji: "手紙", reading: "てがみ", meaning: "surat" },
  { kanji: "切手", reading: "きって", meaning: "perangko" },
  { kanji: "歌手", reading: "かしゅ", meaning: "penyanyi" },
  { kanji: "外国", reading: "がいこく", meaning: "luar negeri" },
  { kanji: "中国", reading: "ちゅうごく", meaning: "Cina" },
  { kanji: "国", reading: "くに", meaning: "negara" },
  { kanji: "会社", reading: "かいしゃ", meaning: "perusahaan" },
  { kanji: "社長", reading: "しゃちょう", meaning: "direktur / direktur utama" },
  { kanji: "社員", reading: "しゃいん", meaning: "pegawai perusahaan" },
  { kanji: "入社", reading: "にゅうしゃ", meaning: "masuk bekerja di perusahaan" },
  { kanji: "駅員", reading: "えきいん", meaning: "petugas stasiun" },
  { kanji: "駅前", reading: "えきまえ", meaning: "depan stasiun" },
  { kanji: "雨季", reading: "うき", meaning: "musim hujan" },
  { kanji: "雨水", reading: "あまみず", meaning: "air hujan" },
  { kanji: "小雨", reading: "こさめ", meaning: "hujan gerimis" },
  { kanji: "水道", reading: "すいどう", meaning: "saluran air / PDAM" },
  { kanji: "書道", reading: "しょどう", meaning: "kaligrafi Jepang (Shodo)" },
  { kanji: "北海道", reading: "ほっかいどう", meaning: "Hokkaido" },
  { kanji: "富士山", reading: "ふじさん", meaning: "Gunung Fuji" },
  { kanji: "火山", reading: "かざん", meaning: "gunung berapi" },
  { kanji: "山口", reading: "やまぐち", meaning: "Yamaguchi" },
  { kanji: "空気", reading: "くうき", meaning: "udara" },
  { kanji: "空港", reading: "くうこう", meaning: "bandara" },
  { kanji: "夜空", reading: "よぞら", meaning: "langit malam" },
  { kanji: "空箱", reading: "からばこ", meaning: "kotak kosong" },
  { kanji: "花屋", reading: "はなや", meaning: "toko bunga" },
  { kanji: "生け花", reading: "いけばな", meaning: "seni merangkai bunga (Ikebana)" },
  { kanji: "花火", reading: "はなび", meaning: "kembang api" },
  { kanji: "花見", reading: "はなみ", meaning: "tradisi melihat bunga sakura (Hanami)" },
  { kanji: "河川", reading: "かせん", meaning: "sungai-sungai / perairan sungai" },
  { kanji: "石川", reading: "いしかわ", meaning: "Ishikawa (nama daerah/orang)" },
  { kanji: "香川", reading: "かがわ", meaning: "Kagawa (nama daerah)" },
  { kanji: "牛肉", reading: "ぎゅうにく", meaning: "daging sapi" },
  { kanji: "牛乳", reading: "ぎゅうにゅう", meaning: "susu sapi" },
  { kanji: "水牛", reading: "すいぎゅう", meaning: "kerbau air" },
  { kanji: "子牛", reading: "こうし", meaning: "anak sapi" },
  { kanji: "子馬", reading: "こうま", meaning: "anak kuda" },
  { kanji: "馬肉", reading: "ばにく", meaning: "daging kuda" },
  { kanji: "馬鹿", reading: "ばか", meaning: "bodoh / konyol" },
  { kanji: "魚屋", reading: "さかなや", meaning: "toko ikan" },
  { kanji: "小魚", reading: "こざかな", meaning: "ikan kecil" },
  { kanji: "金魚", reading: "きんぎょ", meaning: "ikan koki / ikan emas" },
  { kanji: "人魚", reading: "にんぎょ", meaning: "putri duyung" },
  { kanji: "日本人", reading: "にほんじん", meaning: "orang Jepang" },
  { kanji: "女の人", reading: "おんなのひと", meaning: "wanita / perempuan" },
  { kanji: "恋人", reading: "こいびと", meaning: "kekasih / pacar" },
  { kanji: "三人", reading: "さんにん", meaning: "3 orang" },
  { kanji: "一本", reading: "いっぽん", meaning: "1 batang / 1 buah (benda panjang)" },
  { kanji: "日本", reading: "にほん", meaning: "Jepang" },
  { kanji: "二本", reading: "にほん", meaning: "2 batang (benda panjang)" },
  { kanji: "三本", reading: "さんぼん", meaning: "3 batang (benda panjang)" },
  { kanji: "何か", reading: "なにか", meaning: "sesuatu" },
  { kanji: "何分", reading: "なんぷん", meaning: "berapa menit" },
  { kanji: "何回", reading: "なんかい", meaning: "berapa kali" },
  { kanji: "何でも", reading: "なんでも", meaning: "apa saja / apa pun" },
];
